version: '3.9'
services:

  db:
    container_name: fiber_clean_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:15-alpine
    networks:
      - network
    ports:
      - ${HOST_DB_PORT}:${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data


networks:
  network:
    driver: bridge

volumes:
  db_data:
